# creating the docker compose file for the application backend

version : "3.8"


services:
  # mongo service
  mongo1:
    image: mongo:6
    container_name: mongo1
    restart: always
    command: ["mongod","--replSet","res0","--bind-ip-all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-net

  # creating the replica set-1
  mongo2:
    image: mongo:6
    container_name: mongo2
    restart: always
    command: ["mongod","--replSet","res0","--bind-ip-all"]
    ports:
      - "27018:27017"
    networks:
      - mongo-net

  # creating the replica set-2
  mongo3:
    image: mongo:6
    container_name: mongo3
    restart: always
    command: ["mongod","--replSet","res0","--bind-ip-all"]
    ports:
      - "27019:27017"
    networks:
      - mongo-net

networks:
  - mongo-net
